config/routes.rb
Rails.application.routes.draw do

  get 'news/front', to: "news#front"
  get "new/:id", to: "news#show", as: :oneNew
  get 'players/index', to: "players#index"
  get "players/pruebas"
  get 'players/team', to: 'players#team', :as => "teamPage"
  post 'players/team', to: 'players#updateTeam'
  post 'players/teamSeleceted', to: 'players#updateTeam'
  get 'players/userTeam/:id', to: 'players#userTeam', as: 'userTeam'

  get 'admins/edit'=> 'admins#edit'
  post 'admins/:id/edit', :to => 'admins#update'

  #Rutas para Stimulus
  get 'players/teamSelected', :to => "players#searches", :as => "team"
  get 'devise/registrations/isAdmin', :to => "admins#check", :as => "checked"
  get 'devise/registrations/isDel', :to => "admins#check2", :as => "del"

  resources :admins
  resources :news
  resources :players

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  root to: "news#front"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/new.rb
class New < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
  validates :number, presence: true
  validates :position, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :team

  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  def active_for_authentication?
    super && !deleted_at
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
    @usuarios = User.all
  end

  def new
    @usuarios = User.new
  end

  def create
    @usuarios = User.create(params_usuarios)
    if @usuarios.save
      redirect_to admins_path
    else
      render 'new'
    end
  end

  def edit
    puts('----------------Función edit------------------')
    @usuarios = User.find(params[:id])

  end

  def update
    puts('----------------Función update-----------------')
    @usuarios = User.find(params[:id])
    @usuarios.update(params_usuarios)
    redirect_to admins_path
  end

  def check
    @usuario = User.find(params[:user])
    @usuario.admin = params[:admin]
    @usuario.save!
  end

  def check2
    @usuario = User.find(params[:user])
    if params[:del] == "true"
      @usuario.deleted_at = Time.current
    elsif params[:del] == "false"
      @usuario.deleted_at = nil
    end
    @usuario.save!
  end

  private
  def params_usuarios
    params.require(:user).permit(:name, :email, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

    def index
      puts "--------------ENTRO EN EL CONTROLADOR DE NOTICIAS----------------"
      @noticia = New.all.order("created_at").reverse
    end

    def new
      @noticia = New.new
    end

    def create
      @noticia = New.create(params_noticia)
      if @noticia.save
        redirect_to news_index_path
      else
        render 'new'
      end
    end

    def edit
      @noticia = New.find(params[:id])
    end

    def update
      @noticia = New.find(params[:id])
      if @noticia.update(params_noticia)
        redirect_to @noticia
      else
        render 'edit'
      end
    end

    def show
      @noticia = New.find(params[:id])
    end

    def destroy
      @noticia = New.find(params[:id])
      @noticia.destroy
      redirect_to news_index_path
    end

    def front
      @noticia = New.order("created_at").last(3).reverse
    end

    private
    def params_noticia
      params.require(:new).permit(:title,:subtitle,:content,:photo)
    end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :require_login, only: [:updateTeam, :team]

    def index
      @jugador = Player.all
    end

    def new
      @jugador = Player.new
    end

    def create
      @jugador = Player.create(params_jugador)
      if @jugador.save
        redirect_to players_index_path
      else
        render 'new'
      end
    end

    def edit
      @jugador = Player.find(params[:id])
    end

    def update
      @jugador = Player.find(params[:id])
      if @jugador.update(params_jugador)
        redirect_to @jugador
      else
        render 'edit'
      end
    end

    def show
      @jugador = Player.find(params[:id])
    end

    def destroy
      @jugador = Player.find(params[:id])
      @jugador.destroy
      redirect_to players_index_path
    end

    def team
      @porteros = Player.where({:position => 'Portero'})
      @defensas = Player.where({:position => 'Defensa'})
      @mediocentros = Player.where({:position => 'Centrocampista'})
      @delanteros = Player.where({:position => 'Delantero'})
      unless Team.exists? user_id: current_user.id
        puts("------------------Plantilla nueva creada para el usuario---------------------")
        @team = Team.new()
        @team.user_id = current_user.id
        @team.save!
      end
    end

  def updateTeam
    puts("-----------------El usuario ya tiene una plantilla creada---------------------")
    @team = Team.find_by user_id: current_user.id
    @team.update(team_params)
    redirect_to players_team_url, notice: "Plantilla actualizada correctamente"
  end

  def userTeam
    @user = User.find(params[:id])
    @team = Team.find_by user_id: params[:id]
  end

  def searches
    puts "--------------ENTRO EN EL CONTROLADOR----------------"
    #@jugador = Player.where("name LIKE :pos", pos: "#{params[:player]}")
    jugadores = Player.where(name: params[:player])
    pos = params[:pos]
    @jugador = jugadores.first
    if @jugador != nil
      render turbo_stream: turbo_stream.update(pos, partial: "players/jugador", locals:{n:@jugador.name})
    else
      render turbo_stream: turbo_stream.update(pos, partial: "players/jugador", locals:{n:nil})
    end
  end

    private
    def params_jugador
      params.require(:player).permit(:name,:number,:position,:photo)
    end

    def team_params
      params.permit(:PO, :LI, :DCI, :DCD, :LD, :MCI, :MD, :MCD, :EI, :DC, :ED)
    end

    def require_login
      unless signed_in?
        redirect_to new_user_session_url, alert: "Debes iniciar sesión para poder acceder"
      end
    end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  #def edit
  # super
  #end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_navigational_format?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :admin])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :admin])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/admins/edit.html.erb
  <div class="deviseContainer mt-16">
    <!-- Edit  resource_name.to_s.humanize %> -->
    <h2 class="text-center text-blue-600 text-2xl mb-5">Editar usuario (ID: <%=(params[:id])%>)</h2>

    <%= turbo_frame_tag "post" do %>
      <%= render partial: 'form' %>
    <% end %>


    <div class="flex flex-wrap mt-5">
      <%= link_to "Borrar la cuenta", registration_path(@usuarios), data: { confirm: "¿Estás seguro?" }, method: :delete,
                  class: "link w-full" %>
      <%= link_to "Volver", admins_path, class: "link w-full" %>
    </div>

  </div>

app/views/admins/index.html.erb
  <%= render "partials/header" %>

  <div class="container mainContainer">
    <h1 class="text-4xl text-blue-600 mb-5">Lista de usuarios</h1>

    <table class="table-auto w-full">

      <thread>
        <tr>
          <th>Nombre</th>
          <th>Correo</th>
          <th>Creado</th>
          <th>Actualizado</th>
          <th>Admin</th>
          <th>Eliminado</th>
        </tr>
      </thread>

      <tbody data-controller="hello">
        <% @usuarios.each do |usuario| %>
          <% id = usuario.id%>
          <tr class="text-center">
            <td class="border border-blue-600"><%=usuario.name%></td>
            <td class="border border-blue-600"><%=usuario.email%></td>
            <td class="border border-blue-600"><%=usuario.created_at%></td>
            <td class="border border-blue-600"><%=usuario.updated_at%></td>
            <div>
              <% if usuario.admin %>
                <td><input id ="check" name="check" type="checkbox" checked data-id='<%=id%>' data-action="hello#check"/></td>
              <% else %>
                <td><input id ="check" name="check" type="checkbox" data-id='<%=id%>' data-action="hello#check"/></td>
              <% end %>
            </div>
            <div>
              <% if usuario.deleted_at != nil %>
                <td class=""><input id ="check" name="check" type="checkbox" checked data-id='<%=id%>' data-action="hello#check2"/></td>
              <% else %>
                <td class=""><input id ="check" name="check" type="checkbox" data-id='<%=id%>' data-action="hello#check2"/></td>
              <% end %>
            </div>
            <td><%= link_to "Editar usuario", edit_admin_path(usuario.id) , class: "inline-block text-sm px-4 py-2 leading-none border
                font-semibold rounded border-black hover:border-transparent hover:text-teal-500 hover:text-black hover:bg-white mt-4 ml-3 lg:mt-0" %></td>
          </tr>
        <% end %>
      </tbody>

    </table>


  </div>


  <%= render "partials/footer" %>

app/views/admins/new.html.erb
<div class="deviseContainer mt-16">
  <!-- Edit  resource_name.to_s.humanize %> -->
  <h2 class="text-center text-blue-600 text-2xl mb-5">Editar usuario: </h2>
  <%= form_with(model: @usuarios, url: admins_path, class: 'w-full', html: {method: :post}) do |f| %>

    <div class="field">
      <%= f.label :name, "Nombre:", class: "block text-gray-700 text-sm font-bold mb-2"%>
      <%= f.text_field :name, autofocus: true, class: "shadow appearance-none border rounded w-full
      py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="field">
      <%= f.label :email, "Correo:", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "shadow appearance-none border rounded w-full
      py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="field">
      <%= f.label :password, "Contraseña:", class: "block text-gray-700 text-sm font-bold"%>
      <i class="text-xs">(Dejarlo en blanco para no cambiar la contraseña)</i>
      <%= f.password_field :password, autocomplete: "new-password", class: "shadow appearance-none border rounded w-full
      py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      <% if @minimum_password_length %>
        <em class="text-xs text-red-600"><%= @minimum_password_length %> caracteres mínimos</em>
      <% end %>
    </div>

    <div class="field">
      <%= f.label :admin, "¿Administrador?", class: "text-gray-700 text-sm font-bold mr-5"%>
      <%= f.check_box :admin %>
    </div>

    <div class="field text-center">
      <%= f.submit "Actualizar", class: "bg-gray-400 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded focus:outline-none
      focus:shadow-outline mx-auto" %>
    </div>
  <% end %>

  <div class="flex flex-wrap mt-5">
    <%= link_to "Borrar la cuenta", registration_path(@usuarios), data: { confirm: "¿Estás seguro?" }, method: :delete,
                class: "link w-full" %>
    <%= link_to "Volver", admins_path, class: "link w-full" %>
  </div>

</div>

app/views/news/edit.html.erb
<%= render "partials/header" %>
<div class="container mainContainer w-2/3 py-4">
  <h1 class="text-blue-600 text-2xl text-center mb-5">Editar noticia</h1>

  <%= form_with(model: @noticia, url: news_path, class: 'w-full') do |form|  %>

    <div class="flex flex-wrap md:items-center mb-6">
      <div class="w-full">
        <%= form.label :title, "Título: ", class:"text-blue-600 font-bold md:text-right
          mb-1 md:mb-0 pr-4"%>
      </div>
      <div class="w-full">
        <%= form.text_field :title, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2
          px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-600" %>
      </div>
    </div>

    <div class="flex flex-wrap md:items-center mb-6">
      <div class="w-full">
        <%= form.label :subtitle, "Subtítulo: ", class:"text-blue-600 font-bold md:text-right
          mb-1 md:mb-0 pr-4"%>
      </div>
      <div class="w-full">
        <%= form.text_field :subtitle, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2
          px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-600" %>
      </div>
    </div>

    <div class="flex flex-wrap md:items-center mb-6">
      <div class="w-full">
        <%= form.label :content, "Contenido: ", class:"text-blue-600 font-bold md:text-right
          mb-1 md:mb-0 pr-4"%>
      </div>
      <div class="w-full">
        <%= form.text_area :content, rows: 13, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded
        w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-600" %>
      </div>
    </div>

    <div class="flex flex-wrap md:items-center mb-6">
      <div class="w-full">
        <%= form.label :photo, "Enlace a la foto: ", class:"text-blue-600 font-bold md:text-right
          mb-1 md:mb-0 pr-4"%>
      </div>
      <div class="w-full">
        <%= form.text_field :photo, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2
          px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-600" %>
      </div>
    </div>

    <div class="text-center">
      <%= form.submit "Actualizar", class: 'items-center px-4 py-2 m-2 text-white transition-colors bg-gray-400 rounded-lg
      focus:shadow-outline hover:bg-blue-600 font-bold' %>
    </div>

  <% end %>
</div>

<%= render "partials/footer" %>

app/views/news/front.html.erb
<%= render "partials/header" %>
<div class="container mainContainer">
  <div class="my-3">
    <h2 class="text-blue-600 text-4xl">Actualidad del equipo</h2>

    <div class="my-3">

      <%= render "partials/carousel", :locals => { :n => @noticia} %>

      <div class="flex flex-row">

        <div class="flex flex-col w-4/6 mr-5">
          <div class="bg-team bg-cover h-96 w-full p-10">
            <%= link_to "Conoce a la plantilla", players_index_path, class: "text-blue-600 text-semibold text-xl" %>
          </div>
        </div>

        <div class="flex flex-col bg-small-field w-2/6">
          <div class="flex justify-around items-center bg-small-field bg-cover h-96 w-full p-10">
            <%= link_to "Crea tu 11", players_team_path, class: "text-white text-semibold text-4xl" %>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>
<%= render "partials/footer" %>

app/views/news/index.html.erb
<%= render "partials/header" %>
<div class="container mainContainer">
  <h1 class="text-blue-600 text-4xl mb-4">Última hora</h1>

  <div class="grid grid-cols-2 gap-5">
    <% n=1 %>
    <% @noticia.each do |noticia| %>
      <% if n==1 %>
        <div class="col-span-2 text-center rounded shadow-xl mb-8 p-5 bgImg">
          <h2 class="text-2xl font-semibold"> <%= noticia.title %></h2>
          <p> <%= noticia.subtitle %> </p>
          <%= link_to oneNew_path(noticia.id) do %>
            <img src="<%=noticia.photo%>" alt="<%=noticia.title%>" class="noticeImg border-8 border-blue-600 my-4" >
          <% end %>
        </div>
        <h2 class="col-span-2 text-center text-4xl text-blue-600 mb-5">Noticias</h2>
      <% else %>
        <div class="xl:col-span-1 lg:col-span-2 md:col-span-2 sm:col-span-2 border-t-2 border-blue-600 hover:border-transparent">
          <h2 class="text-2xl font-semibold"> <%= noticia.title %></h2>
          <p> <%= noticia.subtitle %> </p>
          <%= link_to oneNew_path(noticia.id) do %>
            <img src="<%=noticia.photo%>" alt="<%=noticia.title%>" class="noticeImg" >
          <% end %>
        </div>
      <% end %>
      <% n = n+1 %>
    <% end %>
  </div>

  <% if signed_in? && current_user.admin %>
    <div class="text-center">
      <a class="inline-flex items-center h-8 px-4 m-2 text-white transition-colors bg-gray-400
        rounded-lg focus:shadow-outline hover:bg-indigo-600" href="<%= new_news_path %>">Redactar noticia</a>
    </div>
    <% end %>

</div>

<%= render "partials/footer" %>

app/views/news/new.html.erb
<%= render "partials/header" %>
<div class="container mainContainer w-2/3 py-4">
  <h1 class="text-blue-600 text-2xl text-center mb-5">Redacción noticia</h1>

  <%= form_with(model: @noticia, url: news_path, class: 'w-full') do |form|  %>

    <div class="flex flex-wrap md:items-center mb-6">
      <div class="w-full">
        <%= form.label :title, "Título: ", class:"text-blue-600 font-bold md:text-right
          mb-1 md:mb-0 pr-4"%>
      </div>
      <div class="w-full">
        <%= form.text_field :title, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2
          px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-600" %>
      </div>
    </div>

    <div class="flex flex-wrap md:items-center mb-6">
      <div class="w-full">
        <%= form.label :subtitle, "Subtítulo: ", class:"text-blue-600 font-bold md:text-right
          mb-1 md:mb-0 pr-4"%>
      </div>
      <div class="w-full">
        <%= form.text_field :subtitle, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2
          px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-600" %>
      </div>
    </div>

    <div class="flex flex-wrap md:items-center mb-6">
      <div class="w-full">
        <%= form.label :content, "Contenido: ", class:"text-blue-600 font-bold md:text-right
          mb-1 md:mb-0 pr-4"%>
      </div>
      <div class="w-full">
        <%= form.text_area :content, rows: 13, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded
        w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-600" %>
      </div>
    </div>

    <div class="flex flex-wrap md:items-center mb-6">
      <div class="w-full">
        <%= form.label :photo, "Enlace a la foto: ", class:"text-blue-600 font-bold md:text-right
          mb-1 md:mb-0 pr-4"%>
      </div>
      <div class="w-full">
        <%= form.text_field :photo, class: "bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2
          px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-600" %>
      </div>
    </div>

    <div class="text-center">
      <%= form.submit "Publicar", class: 'items-center px-4 py-2 m-2 text-white transition-colors bg-gray-400 rounded-lg
      focus:shadow-outline hover:bg-blue-600 font-bold' %>
    </div>

  <% end %>
</div>

<%= render "partials/footer" %>

app/views/news/show.html.erb
<%= render "partials/header" %>
<div class="container mainContainer flex flex-wrap">

  <div class="w-full mb-5 border-b border-blue-600">
    <h1 class="text-blue-600 text-4xl"> <%= @noticia.title %> </h1>
    <h2 class="text-gray-500 text-xl"> <%= @noticia.subtitle %> </h2>
  </div>
  <!--<hr class="w-2/3 mx-auto mt-2 mb-4">-->
  <p> <%= @noticia.content %> </p>
  <img src="<%= @noticia.photo %>" alt="<%= @noticia.title%>" class="noticeImg mt-5">

  <div class="w-full text-center mt-5">
    <% if signed_in? && current_user.admin %>
      <%= link_to "Editar", edit_news_path(@noticia.id), class: "inline-flex items-center h-8 px-4 m-2
      text-white transition-colors bg-gray-400 rounded-lg focus:shadow-outline hover:bg-blue-600" %>
      <%= link_to "Eliminar", news_path(@noticia.id), method: :delete, class: "inline-flex items-center h-8 px-4 m-2
        text-white transition-colors bg-gray-400 rounded-lg focus:shadow-outline hover:bg-red-600" %>
    <% end %>
    <%= link_to "Volver", news_index_path, class: "inline-flex items-center h-8 px-4 m-2 text-white transition-colors
      bg-gray-400 rounded-lg focus:shadow-outline hover:bg-blue-600" %>
  </div>

</div>
<%= render "partials/footer" %>

app/views/partials/_footer.html.erb
<footer class="bottom-0 bg-white w-full mt-4 pt-4">
  <div class="mx-auto">

    <div class="mb-4 text-center">
      <p> Contenido del footer </p>
    </div>

    <div class="flex flex-row justify-center align-middle items-middle py-5 w-full bg-gray-400">
      <p class="my-auto mr-4"> © 2021 Copyright: </p>
      <a href="https://21ninjas.es/" target="_blank" > <%= image_tag "logo.png" %> </a>
    </div>

  </div>
</footer>

app/views/partials/_header.html.erb
<nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6 px-16 mb-3 bg-gray-400">

  <div class="flex items-center flex-shrink-0 text-blue-600 mr-6">
    <a href="<%= root_path %>"> <%= image_tag "escudo.png", size: "50x50" %></a>
    <a class="font-semibold text-xl tracking-tight" href="<%= root_path %>">  21Madridistas</a>
  </div>

  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="lg:flex-grow">
      <a class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"
         href="<%= news_index_path %>">Noticias</a>
      <a class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"
         href="<%= players_index_path %>">Plantilla</a>
      <a class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"
         href="<%= players_team_path %>">Crea tu 11</a>
      <% if signed_in? && current_user.admin %>
        <a class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"
           href=<%= admins_path %>>Gestión de usuarios</a>
      <% end %>
    </div>
    <div>
      <% if signed_in? %>
        <%= link_to "Editar usuario", edit_user_registration_path , class: "inline-block text-sm px-4 py-2 leading-none border
            font-semibold rounded border-black hover:border-transparent hover:text-teal-500 hover:text-black hover:bg-white mt-4 ml-3 lg:mt-0" %>
        <%= link_to "Cerrar sesión", destroy_user_session_path, :method => :delete, class: "inline-block text-sm px-4 py-2 leading-none border
            font-semibold rounded border-black hover:border-transparent hover:text-teal-500 hover:text-black hover:bg-white mt-4 ml-3 lg:mt-0" %>
      <% else %>
        <a href="<%= new_user_registration_path %>" class="inline-block text-sm px-4 py-2 leading-none border font-semibold rounded border-black
            hover:border-transparent hover:text-teal-500 hover:text-black hover:bg-white mt-4 lg:mt-0">Registrarse</a>
        <a href="<%= new_user_session_path %>" class="inline-block text-sm px-4 py-2 leading-none border font-semibold rounded border-black
            hover:border-transparent hover:text-teal-500 hover:text-black hover:bg-white mt-4 ml-3 lg:mt-0">Iniciar sesión</a>
      <% end %>

    </div>
  </div>
</nav>

app/views/players/_pos.html.erb
<div class="w-full flex flex-wrap mb-4">
  <div class="w-full mb-5 border-b border-blue-600">
    <h2 class="text-gray-500 text-2xl"> <%= x %>s: </h2>
  </div>
  <% @jugador.each do |jugador| %>
    <% if jugador.position == x %>
      <div class="mb-5 w-1/4 h-auto">
        <a href="<%= player_path(jugador.id) %>" class="text-blue-600 fuente"> <%= jugador.name %> </a>
        <p class="text-blue-600 fuente">  </p>
        <img src="<%=jugador.photo%>" alt="<%=jugador.name%>">
        <!--<%= link_to "Eliminar", player_path(jugador.id), method: :delete %>-->
      </div>
    <% end %>
  <% end %>
</div>

app/views/players/index.html.erb
<%= render "partials/header" %>
<div class="container mainContainer">
  <h1 class="text-blue-600 text-4xl mb-5"> Plantilla del primer equipo</h1>

  <%= render :partial => "players/pos", :locals => { :x => "Portero"} %>
  <%= render :partial => "players/pos", :locals => { :x => "Defensa"} %>
  <%= render :partial => "players/pos", :locals => { :x => "Centrocampista"} %>
  <%= render :partial => "players/pos", :locals => { :x => "Delantero"} %>

  <div class="text-center">
    <% if signed_in? && current_user.admin %>
      <a class="inline-flex items-center h-8 px-4 m-2 text-white transition-colors bg-gray-400
      rounded-lg focus:shadow-outline hover:bg-indigo-600" href="<%= new_player_path %>">Añadir nuevo jugador</a>
    <% end %>
  </div>

</div>

<%= render "partials/footer" %>

app/views/players/pruebas.html.erb
<%= render "partials/header" %>
<div class="container mainContainer">

  <div>
    <%= form_with url: search_players_path do |form| %>
      <%= form.collection_select 'search_term', Player.where({:position => 'Portero'}), :name, :name %>
      <%= form.submit "Search", data: {disable_with: false}%>
    <% end %>
  </div>


</div>
<%= render "partials/footer" %>